# Generated by Django 4.0.4 on 2023-05-22 15:07

import chatapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=chatapp.models.upload_location_groupchat_logo)),
                ('name', models.TextField(max_length=60)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=chatapp.models.upload_location_profile_image)),
                ('friends', models.ManyToManyField(blank=True, related_name='profile_friends', to='chatapp.profile')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=chatapp.models.upload_location_groupchat_message)),
                ('text', models.TextField(max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatapp.profile')),
                ('belongs_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatapp.groupchat')),
            ],
        ),
        migrations.AddField(
            model_name='groupchat',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admins', to='chatapp.profile'),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to='chatapp.profile'),
        ),
        migrations.CreateModel(
            name='FriendsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_received', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who_received', to='chatapp.profile')),
                ('who_send', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who_send', to='chatapp.profile')),
            ],
        ),
    ]
