# Generated by Django 4.0.4 on 2023-05-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='date',
            field=models.DateTimeField(blank=True, default='2023-05-04_17:38:02'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default='2023-05-04_17:38:02'),
        ),
    ]
