# Generated by Django 4.0.4 on 2023-05-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_alter_groupchat_date_alter_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admins', to='chatapp.profile'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to='chatapp.profile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
