# Generated by Django 4.0.4 on 2023-05-05 14:28

import chatapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_groupchat_admins_alter_groupchat_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=chatapp.models.upload_location_groupchat_logo),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=chatapp.models.upload_location_groupchat_logo),
        ),
    ]
