# Generated by Django 4.0.4 on 2023-08-06 08:28

import chatapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_groupchat_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=chatapp.models.upload_location_groupchat_message)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='files',
            field=models.ManyToManyField(to='chatapp.file'),
        ),
    ]
