# Generated by Django 4.0.4 on 2023-08-06 08:52

import chatapp.models
import chatapp.validations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_file_message_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='belongs_to',
        ),
        migrations.AddField(
            model_name='file',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatapp.message'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=chatapp.models.upload_location_groupchat_message, validators=[chatapp.validations.validate_file_extension]),
        ),
    ]
