# Generated by Django 4.0.4 on 2023-05-06 06:39

import chatapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_profile_friends_alter_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=chatapp.models.upload_location_profile_image),
        ),
    ]
