# Generated by Django 4.0.4 on 2023-08-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_message_belongs_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='belongs_to',
        ),
        migrations.AlterField(
            model_name='message',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='chatapp.file'),
        ),
    ]
