# Generated by Django 4.0.4 on 2023-08-07 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0009_alter_message_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatapp.profile'),
        ),
    ]
