# Generated by Django 4.0.4 on 2023-08-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_groupchat_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
