# Generated by Django 4.0.4 on 2023-08-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0011_profile_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
