# Generated by Django 4.0.4 on 2023-08-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0012_alter_profile_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
